Replace XML character codes with real character for render
Arkezar/DocFx.Plugins.Kroki pull request #1
Opened 2021-06-30 13:46 UTC by agent00jackson

Diagrams as code can be included in XML /// comments, however certain characters are preprocessed and therefore aren't compiled into diagrams correctly.

2021-06-30 14:12 UTC, Arkezar requested changes
Could you also provide a sample diagram code that's causing problem?

2021-06-30 14:12 UTC, Arkezar commented on DocFx.Plugins.Kroki/Renderers/KrokiRenderer.cs
> +      var code = CodeCleanup(token.Code);
I'd consider moving this operation to KrokiPayload class.

2021-06-30 14:12 UTC, Arkezar commented on DocFx.Plugins.Kroki/Renderers/KrokiRenderer.cs
> +      return raw.Replace("&amp;", "&")
I think `System.Net.WebUtility.DecodeHtml` might be a better solution here but it would require some testing.

2021-06-30 14:39 UTC, agent00jackson commented
Here's a sample XML comment snippet:
```xml
/// <summary>
/// Interaction logic for App.xaml.
/// </summary>
/// <remarks>
/// The shell is a Windows WPF application that inherits from the PrismApplication base class which implements bootstrapping logic to allow for the use of Prism's libraries.
/// 
/// <![CDATA[
/// ```plantuml
/// Prism.Wpf.PrismApplication <|-- Shell.App
/// Shell.App : abstract void RegisterTypes()
/// Shell.App : abstract Window CreateShell()
/// Shell.App : virtual void ConfigureModuleCatalog()
/// ```
/// ]]>
```

The '<' symbol is replaced with a '\&lt;' and when passed to Kroki, it results in a 404 error being rendered. I'll circle back to making the requested changes sometime this week.

2021-07-15 18:06 UTC, agent00jackson commented
Verified that `System.Net.WebUtility.HtmlDecode()` works for internal docs.

2021-07-15 19:09 UTC, merged